behaviors:
  CoverageControllerPPO:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 8
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    max_steps: 30000000
    time_horizon: 2500
    summary_freq: 10000
    
environment_parameters:
  spawnPadding:
    curriculum:
      - name: Lesson1
        value: 150.0   
        completion_criteria:
          measure: reward
          behavior: CoverageControllerPPO
          signal_smoothing: false
          min_lesson_length: 100
          threshold: 0.7

      - name: Lesson2
        value: 50.0
        completion_criteria:
          measure: reward
          behavior: CoverageControllerPPO
          signal_smoothing: false
          min_lesson_length: 100
          threshold: 0.8

      - name: Lesson3
        value: 0.0
        completion_criteria:
          measure: reward
          behavior: CoverageControllerPPO
          signal_smoothing: false
          min_lesson_length: 100
          threshold: 0.1

